export const PREDICTION_REQUEST = 'PREDICTION_REQUEST';
export const PREDICTION_SUCCESS = 'PREDICTION_SUCCESS';
export const PREDICTION_FAIL = 'PREDICTION_FAIL';
export const PREDICTION_RESET = 'PREDICTION_RESET';
