# Generated by Django 3.1.4 on 2021-10-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('book_length_tot', models.IntegerField(blank=True, default=0, null=True)),
                ('book_length_avg', models.IntegerField(blank=True, default=0, null=True)),
                ('price_tot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('review', models.BooleanField(default=False)),
                ('min_listened', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('completion', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('support_requests', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('last_visited', models.BooleanField(default=False)),
                ('purchase_date', models.IntegerField(blank=True, default=0, null=True)),
                ('target', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
