# Generated by Django 3.1.4 on 2021-10-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Prediction',
        ),
    ]
