# Generated by Django 3.1.4 on 2021-10-07 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211006_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prediction',
            name='last_visited',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
